## Crear una nueva pelicula POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title" : 1,
    "year" : 1975,
    "director" : "Francis Ford Coppola",
    "duration" : 175,
}

### recuperar todas las peliculas
GET  http://localhost:1234/movies

### Recuperar una pelicula pir ID
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar todas las peliculas por un género
GET http://localhost:1234/movies?genre=action
